- server/.eslintignore
Prevents linter from linting certain files.
> Add missing eslintignore file in server

- web/src/index.css
Add brand fonts and colors as CSS variables.
> Add common font and colors

- .travis.yml
- server/package.json
- server/yarn.lock
Added pre-push hook that lints code before pushing.
Also added compile step in travis for the backend
> Add pre-push hook to server side

- web/.gcloudignore
I think there was some merge conflict that was not properly fixed previously so here's a really quick fix!
> Fix erroneous gcloudignore path

- server/.eslintrc.json
- server/package.json
- server/src/index.ts
- server/yarn.lock
- web/.eslintrc.json
- web/src/App.test.tsx
- web/src/App.tsx
- web/src/Routes.tsx
- web/src/index.tsx
Closes #31 
- Adding of import sorting rules to `web/` and `server/` dirs as suggested with @ifhuang
- Fixed existing imports according to this rule by running `yarn fix` 😃
> Add import order rules

- web/README.md
Done up an ascii tree with descriptions of the major file and folders used in the project.
> Add folder structure tree to web README

- web/app.yaml
Previously my handlers are not inclusive enough and app routing didn't work for prod :( But I've fixed it! 😄
> Fix FE app.yaml for deployment

- server/src/api/customers.ts
- server/src/api/index.ts
- server/src/interfaces.ts
- server/src/services/customers.ts
- server/src/services/index.ts
- server/src/storage/customers.ts
- server/src/storage/datastore.ts
- server/src/storage/index.ts
- Added customer getter
- Added `datastore.ts`, a file that contains datastore wrappers. `getWithId` strips the KEY_SYMBOL from the GetResponse object, and adds an `id` field to allow better typing throughout the entire repo.
- Changed some exports to default exports (for the files that I touched in this PR, will change the rest in other PRs)
Fetch my branch
```
cd /server
yarn
yarn start:dev
```
Send a request to `http://localhost:5000/customers/5634161670881280` (our dear sample customer)
> Add customer getter

- web/package.json
- web/src/components/common/CardImage.tsx
- web/src/components/common/LazyWrapper.tsx
- web/yarn.lock
- Added a `LazyWrapper` that only renders children components when the component is in view.
- Wrapped `ListingCard` images with `LazyWrapper` to lazy load images for performance
> Add lazy loading for images

- server/src/api/index.ts
- server/src/api/listings.ts
- server/src/interfaces.ts
- server/src/services/index.ts
- server/src/services/listings.ts
- server/src/storage/datastore.ts
- server/src/storage/index.ts
- server/src/storage/listings.ts
Part of issue #47
- Added an endpoint to get all listings
- Added datastore wrapper for getting all with Id 
Fetch my branch
```
cd server
yarn 
yarn start:dev
```
`http://localhost:5000/listings` should return all listings (along with their ids) that are in the db :D 
Here is the response I got:
```
[
{
"oldPrice": {
"dollars": 100,
"currency": "SGD",
"cents": 0
},
"listingStatus": "ongoing",
"merchantId": 5644004762845184,
"imgUrl": "https://images.unsplash.com/photo-1512221472476-7e439affc029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
"price": {
"currency": "SGD",
"cents": 0,
"dollars": 85
},
"name": "Airpods",
"numPaid": 0,
"numCompleted": 0,
"description": "Cheap airpods suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est …
```
> Add listings getter

- server/app.yaml
- server/package.json
- server/src/index.ts
- server/yarn.lock
- web/.env.development
- web/.env.production
Previously, there was a problem sending requests to the server endpoints from the web because they are have different addresses.
This resolves that issue.
This also exposes 'Location' header which is used in POST response to tell the client the location of inserted resource.
> Add CORS to express router

- web/src/Routes.tsx
- Added lazy loading of customer and merchant routes. Now, Customer and Merchant Contexts will only be loaded for the appropriate routes instead of both being loaded on first render.
> Lazy load merchant and customer routes

- server/src/services/commits.ts
- web/src/components/merchant/listing-details/CommittedCustomerStatuses.tsx
- web/src/components/merchant/listing-details/PaidCustomerCard.tsx
- web/src/components/merchant/listing-details/PaidCustomerCollection.tsx
- web/src/components/merchant/listings/index.tsx
- web/src/interfaces.ts
- Used the PaidCustomerCollection component created in #172 to show paid customers in ListingDetails page.
Part of #7.
> Show PaidCustomerCollection in ListingDetails page of successful listing

- web/src/components/customer/explore/MyCommitsButton.tsx
- web/src/components/customer/explore/index.tsx
- Styled My Commits button in Explore page to look like the UI Mock
> Style my commits button in Explore

- web/src/components/customer/my-commits/Commits.tsx
- web/src/components/customer/my-commits/index.tsx
- web/src/index.css
- Styled headers in customer pages to look like UI Mock
> Style customer headers

- server/src/api/commits.ts
- server/src/api/customers.ts
- server/src/api/listings.ts
- server/src/api/merchants.ts
- server/src/index.ts
- server/src/middleware/customer-auth.ts
- server/src/middleware/error-handler.ts
- server/src/middleware/merchant-auth.ts
- server/src/middleware/validation/phone-number.ts
- server/src/services/commits.ts
- server/src/utils/http-errors.ts
- server/tests/integration/commits.test.ts
- server/tests/integration/customers.test.ts
- server/tests/integration/listings.test.ts
- server/tests/integration/merchants.test.ts
Closes #115 
- Added `HttpError` base class which comes with the appropriate status code and error message for each error
- Updated tests with the specific error code
* Also standardised error message phrasing for some error messages 
- Handle Datastore errors and map each error to a specific `HttpError`.
> Add server http error classes

- web/src/custom-typings/window/index.d.ts
- web/src/interfaces.ts
- web/src/microapps.ts
To be merged after #219 
(No logic and behavioural changes!)
- Add types to microapps sdk, remove all uses of `any` in our app 🥳
> Type microapps sdk

- web/src/components/customer/listing-details/ActionBar.tsx
- Add `Item Delivered` action button. (Not sure why it was left as a todo previously haha)
> Add delivered action button

- web/src/components/customer/listing-details/CommitFeedbackPrompt.tsx
- Linked Manage button on commit prompt to My Commits page (was left as a TODO)
> Link commit prompt Manage button to my-commits page

- web/src/components/customer/listing-details/contexts/CommitContext.tsx
**Duplicate of PR #231, because I accidentally merged it into the wrong branch**
> [Reopen] Add loading prompt for commiting and uncommitting
