server/README.md, server/package.json, server/src/index.ts
Changes made:
- Changed `yarn start` command to run compiled code for production
- Added `yarn start:dev` command to run current code for development
Previously `yarn start` command ran code in development mode which caused error when deployed to the server. This PR fixes that problem.
=> Fix server start script for production

web/.eslintrc.json, web/src/Routes.tsx, web/src/components/common/Card.tsx, web/src/components/common/CardImage.tsx, web/src/components/common/ListingCard.tsx, web/src/components/common/ListingPrice.tsx, web/src/components/common/StrippedCol.tsx, web/src/components/design-samples/index.tsx, web/src/index.css, web/src/interfaces.ts
- Added Card and ListingCard components, as well as smaller components used to build it.
- Added a temporary `/design-samples` endpoint for us to place our component designs there for testing and previewing before they are added into the app. Will be removed or kept as a dev env only endpoint in the future.
Currently built for mobile view so it will look really stretched and ugly if you don't change it to mobile view haha.
Because I deployed it haha
[https://gpay-group-buy.an.r.appspot.com/design-samples](https://gpay-group-buy.an.r.appspot.com/design-samples)
OR
Fetch branch then
```
cd web
yarn
yarn start
```
And then navigate to `http://localhost:3000/design-samples` and you should see the page in the screenshot above :)
=> Add Card components

server/src/index.ts
Force processes to be killed because previously we kept getting errors like:
```
Error: listen EADDRINUSE: address already in use :::5000
...
[nodemon] app crashed - waiting for file changes before starting...
```
=> Add stop handler on termination signals

server/src/api/merchants.ts, server/src/services/merchants.ts, server/src/storage/merchants.ts
Previously, I added these codes to setup project structure.
But these are not used yet and are not standardised with getCustomer operations which have better style/structure.
So, I am removing these.
=> Remove unused merchant operations

server/src/api/customers.ts, server/src/interfaces.ts, server/src/services/customers.ts, server/src/storage/customers.ts, server/src/storage/datastore.ts, server/src/storage/interfaces.ts, server/src/storage/listings.ts
- Added numCommits to customer getter response. Num commits is retrieved by querying `Commits` and filtering by customerId and listingStatus
Fetch my branch
```
cd server
yarn
yarn start:dev
```
Make a request to `http://localhost:5000/customers/5634161670881280` (our dear customer) and there will be a new `numCommits` field added. Our dear customer here should have 1 commit.
=> Add numCommits to get customer response

web/src/components/common/CardImage.tsx, web/src/components/common/ListingCard.tsx
Instead of wrapping `CardImage` with `LazyWrapper`, lazy load the entire `ListingCard` instead.
The loading of image after the rest of the card component causes the horizontal mode of `ListingCard` to not work as intended.
**Before:**
**After:**
=> Lazy load ListingCard instead of CardImage

web/src/Routes.tsx, web/src/api.ts, web/src/components/common/BackButton.tsx, web/src/components/common/CommitProgress.tsx, web/src/components/common/DeadlineTag.tsx, web/src/components/common/ListingDescription.tsx, web/src/components/common/ListingPrice.tsx, web/src/components/customer/explore/ListingCollection.tsx, web/src/components/customer/listing-details/ListingDetails.tsx, web/src/components/customer/listing-details/index.tsx, web/src/components/listing-details/index.tsx, web/src/index.css
Closes #16 
- Added a listing details page that users are routed to when they click on a listing in the explore page or directly visit `/listing/:id`
- Wired up the back navigation in the listing details page when users click on the back button
* If user came from the Explore page, they will go back in browser history
* If user came from elsewhere (eg. from a shared link), clicking back will navigate them to the explore page
- `/listing/:id` first routes to `src/components/listing-details` before showing the contents of `src/components/customer/listing-details`.
* I added this extra layer of abstraction because merchants would see slightly different content from customers, and we don't really want to bloat up the components by making it a shared page.
* This shared page in …
=> Add listing details page

.travis.yml, server/README.md, server/package.json, server/tests/datastore-setup.ts, server/tests/datastore-teardown.ts, server/tests/fixtures/customers.ts, server/tests/integration/customers.test.ts, server/yarn.lock
Closes #86 
- Added README on how to run the datastore emulator locally
- Added travis script to download gcloud sdk and datastore emulator for backend tests, and run the datastore emulator as a background task before starting the tests
- Added some customer test fixtures and a simple test to the get customers endpoint
- Added setup and teardown scripts to add test fixtures and reset the emulator datastore before and after all tests
You can view the test log here: https://travis-ci.org/github/googleinterns/gpay-group-buy/jobs/704369214#L302
=> Setup datastore testing

server/src/api/merchants.ts, server/src/interfaces.ts, server/src/services/merchants.ts, server/src/storage/datastore.ts, server/src/storage/interfaces.ts, server/src/storage/merchants.ts
Add get merchants API that allows filters using query parameters.
**To do in future PRs:**
- (#87) Restrict response so that only the merchants themselves can get all the fields but other merchants/customers can get only public fields like name.
- Right now, everyone can get all merchant objects including all the fields (name, email, VPA) except for password.
=> Create Get All Merchants API

web/public/index.html, web/src/custom-typings/window/index.d.ts, web/src/microapps.ts
Add microapps API to our app, we can now use the api by importing `import microapps from 'microapps';`
When we add microapps API through the script tag in `index.html`, we can access it via `window.microapps`. 
However, since we are using TypeScript, TypeScript will complain because microapps is not a known property of Window. A common workaround is to simply `declare const window: any`. However we would want to avoid that as we want to retain the typechecking of window's existing properties. So in this PR, I extended the Window interface in `web/src/custom-typings/window/index.d.ts` by adding a `microapps` property instead.
=> Add microapps API

server/src/api/customers.ts, server/src/interfaces.ts, server/src/services/customers.ts, server/src/storage/customers.ts
Part of #58 
- The `POST /customers` endpoint now returns the data of an existing customer if another customer with the same gpayId already exists. So now this is the updated behavior of `POST /customers`:
* If a customer with the same gpayId exists, response body will include the details of the customer in the response body (similar to a get request), with status code 200
* If the customer does not exists, this customer will be added to the datastore, and the reponse body will include the details of this newly added customer, with status code 201.
**Justification for using the same endpoint:**
We do not separate the endpoint because on the client side, we have no idea if a customer with the same gpayId already exists or not in our own database. Since we are using the Spot identity API to …
=> Make POST /customers endpoint return existing customer if customer with gpayId already exists

web/src/api.ts, web/src/components/common/CommitsBadge.tsx, web/src/components/customer/explore/index.tsx, web/src/interfaces.ts, web/src/microapps.ts
Closes #58 
To be merged after #88 and #96 
- Customers can now login via the microapps identity API
- After calling the identity API, call our sever login endpoint to signin/signup the customer and get the customer details
- Added a temporary "Get Identity" button to trigger this login process
- Clicking that button will update the numCommits in the NumCommitsContext
Visit the app via GPay Spot app. 
Click on the "Get Identity" button. Permissions dialog should be triggered and you should see the Commits badge appear.
Sample network request & response from inspect:
=> Add customer signinsignup on client side

server/src/api/commits.ts, server/src/api/index.ts, server/src/index.ts, server/src/interfaces.ts, server/src/services/commits.ts, server/src/services/index.ts, server/src/storage/commits.ts, server/src/storage/index.ts, server/tests/datastore-setup.ts, server/tests/fixtures/commits.ts, server/tests/fixtures/customers.ts, server/tests/fixtures/listings.ts, server/tests/integration/commits.test.ts, server/tests/integration/customers.test.ts
Closes #109 
- Add endpoint to get all commits that accept query parameters "listingId" and "customerId"
- Added tests for commits getter
**Not in this PR:**
-  Handling of proper error codes, added as a TODO.
Invalid query param:
Invalid query value:
Non-existent id provided:
Successful case
Chaining query params
=> Create get all commits endpoint

server/src/api/commits.ts, server/src/api/customers.ts, server/src/constants/customer.ts, server/src/constants/default-payload.ts, server/src/interfaces.ts, server/src/services/commits.ts, server/src/storage/commits.ts, server/src/storage/datastore.ts
Closes #110 
- Added endpoint to add commits
- Endpoint contains customer auth, so need a valid auth token to make the request
- Added `insertAndUpdateRelatedEntity()` transaction in the datastore layer  
**Not in this PR (to be done in future PRs):**
- Ensure that the user is making the request for themselves (can do this by checking the the decoded customer `sub` against the gpayId of the customer in the request.
- Proper parsing of req.body json to be of CommitRequest type
- Returning of proper error codes
**Missing auth header**
**Using invalid listing or customer id**
**Customer has hit max commits**
**Successful request**
**Screenshot of datastore to show consistency between commit data and listing numCommits**
=> Create add commit endpt

server/src/api/commits.ts, server/src/api/customers.ts, server/src/services/commits.ts, server/src/storage/commits.ts, server/src/storage/datastore.ts
Closes #111 
- Added endpoint to delete commits
- Endpoint contains customer auth, so need a valid auth token to make the request
- Added `deleteAndUpdateRelatedEntity()` transaction in the datastore layer
**Not in this PR (to be done in future PRs):**
- Ensure that the user is making the request for themselves
- Returning of proper error codes
**Deleting a non-existent Id**
**Deleting an invalid id**
**Deleting a non-ongoing listing**
**Successful delete**
**Before deleting in Datastore**
**After deleting in Datastore**
**Affected listing now has numCommits of 1 instead of 2**
=> Add delete commit endpoint

web/src/components/customer/explore/ListingCollection.tsx
A really quick fix on the UI problem on Explore page.
Previously, the problem came about when there are listing cards of uneven height because listing cards would try to take up whatever space without trying to "keep to rows". This PR fixes that.
**Before**
**After**
=> Fix listing rows in explore

server/src/services/commits.ts, server/src/storage/commits.ts, server/src/storage/customers.ts, server/src/storage/datastore.ts, server/src/storage/merchants.ts
Merge after #131 
- Previously, we are able to create multiple commits with the same `customerId` and `listingId`. This is not desirable, and we should enforce in the insertion transaction that another commit with the same `customerId` and `listingId` should not already exist.
- Added `uniqueInsertInTransaction` in datastore layer to refactor out unique insertion logic.
=> Only allow unique commits to be created

web/src/api.ts, web/src/components/customer/Routes.tsx, web/src/components/customer/explore/index.tsx, web/src/components/customer/my-commits/Commits.tsx, web/src/components/customer/my-commits/index.tsx, web/src/interfaces.ts, web/src/utils/commit-status/commit-status.test.ts, web/src/utils/commit-status/index.ts
To be merged after #138 
Part of #14 
- Added basic My Commits page that shows the commit JSON 
- Added button (unstyled yet) on Explore page to link to My Commits page
=> Add basic my commits page

web/src/components/customer/listing-details/ActionBar.tsx, web/src/components/customer/listing-details/CommitFeedbackPrompt.tsx, web/src/components/customer/listing-details/contexts/CommitContext.tsx, web/src/components/customer/listing-details/contexts/ListingDetailsContext.tsx, web/src/components/customer/listing-details/index.tsx
To be merged after #138 
Refactoring PR, no behavioural changes from #138
- After #138, `ListingDetailsContext` seems to be in charge of too many things (it touched on listings, commit, customer). This PR moves out all commit related logic (which includes updating of customer) to `CommitContext`. `ListingDetailsContext` is now just in charge of listing & page related logic.
=> Refactor out CommitContext

server/src/interfaces.ts, server/src/services/commits.ts, server/src/storage/customers.ts, web/src/components/common/CommitsBadge.tsx, web/src/interfaces.ts
- `numOngoingCommits` is changed to `numUsedCommits`(num ongoing + num successful) because customers are not given back their commits UNTIL they have paid for their commits. 
- Refactored `getNumUsedCommits` to `withNumUsedCommits` which gets the `numUsedCommits` and also does the adding of `numUsedCommits` to the passed in customer data
=> Change numOngoingCommits to numUsedCommits

web/src/components/merchant/listings/index.tsx
- Added an Add Listing button in Listings page next to the header.
- Previously, merchant cannot navigate to Add Listing page if they already have a listing.
- This button component is a child of the PageBody component although it is shown next to the header.
=> Put Add Listing button in Listings page when listings are not empty

.travis.yml
- This piece of code that I am removing is left behind previously when I was trying out on the installation of google cloud sdk on travis. The actual working installation is done on lines 10-16. Removing this because I just realised I forgot to remove it previously! :(
=> Remove dead code from travis.yml

.travis.yml, server/package.json, web/README.md, web/package.json
- Removed running of linter in posttest script
* Running `yarn test` shall only run tests instead of doing both testing and linting.
* In our [travis script](https://github.com/googleinterns/gpay-group-buy/blob/master/.travis.yml#L25), we run `yarn lint` before running `yarn test`. This is because we would like to feedback lint failures to the user asap. 
Keeping the posstest linting results in checking for linting twice in the travis script, which is unnecessary. 
- Renamed `compile` script on client side to `typecheck` instead. Our client side uses Babel to compile instead of the typescript compiler. Running `tsc` on the frontend will not emit compiled files because of the `noEmit` compiler option [here](https://github.com/googleinterns/gpay-group-buy/blob/9d917e4ba9dd1e4391624900d143239 …
=> Modify package.json scripts

server/src/api/commits.ts, server/src/constants/default-payload.ts, server/src/interfaces.ts, server/src/services/commits.ts, server/src/storage/commits.ts, server/src/storage/datastore.ts
Closes #150
- Added endpoint to pay for commits
- Added `editAndUpdateRelatedEntity` to datastore layer,  and refactored out `updateEntityInTransaction` in datastore layer
**TODOs, Not in this PR**
- Ensure that commit belongs to the authenticated customer
- Updating of commit interface on client side to include address and contact number
- Validating of paymentData (#153)
- Updating of customer's address and contact number
**Non-existent commit id**
**Invalid commit id type**
**Successful payment**
**Updated commit after successful payment**
**Updated listing after successful payment**
=> Add pay for commit endpoint

web/src/api.ts, web/src/components/customer/listing-details/ActionBar.tsx, web/src/components/customer/listing-details/contexts/CommitContext.tsx, web/src/interfaces.ts, web/src/utils/commit-status/commit-status.test.ts
To be merged after #151 and #153
Part of #13 
- Add payment flow to frontend after clicking on the "Pay" button
**Not in this PR**
- Delivery details form, currently using dummy delivery data for payment
(I manually changed the `commitStatus` for the commit to be "successful" in datastore temporarily to try it out for this listing)
What happens before and after I click the Pay button:
=> Add basic customer payment flow

web/src/components/customer/merchant-profile/index.tsx
- Added listingStatus as a query param to the listings when fetching merchant profile
* This fixes the bug that we saw during meeting just now. Apparently, changes has been made to the backend before my PR #158 got merged which enforces that listings has to be filtered by `listingStatus` after filtering by `merchantId`.
=> Only show ongoing listings on merchant profile page

server/index.yaml, web/src/components/customer/explore/index.tsx
- Only show ongoing listings, and order listings by earliest deadline
**Screenshot**
(The first listing still has 'ongoing' status because #93 is not implemented yet)
=> Order explore listings by earliest deadline and only show ongoing listings

server/src/storage/commits.ts, server/src/storage/customers.ts, server/src/storage/datastore.ts, server/src/storage/listings.ts, server/src/storage/merchants.ts
Closes #161
**Please refer to #161 for background for this PR**
- Added higher order function `makeTransaction` in datastore layer
- Added "building blocks" for transactions, such as `getEntityInTransaction` and other functions ending with `InTransaction` 
- Replaced all existing transaction functions like `addAndUpdateRelatedEntity` with `makeTransaction` and the appropriate "building blocks". 
So now, instead of
```
const commitId = await addAndUpdateRelatedEntity(
COMMIT_KIND,
commit,
LISTING_KIND,
commit.listingId,
[
{
property: 'numCommits',
op: 'add',
value: 1,
},
],
uniqueProperties
);
```
We now do
```
const [commitId] = await makeTransaction(
addInTransaction(COMMIT_KIND, commit, uniqueProperties),
updateInTransaction(LISTING_KIND, commit.listingId, [
{
property: 'numCommits', …
```
=> Refactor datastore to use HOF transaction

web/src/components/customer/contexts/CustomerContext.tsx, web/src/interfaces.ts, web/src/microapps.ts
Microapps API returns a  different identity token every time we try to get identity, even when it is the same gpay user and the previous token has not expired. This resulted in unnecessary rerenders of our app that listens to change the value of `idToken` in CustomerContext. This is not ideal, and we want to use the same `idToken` if it is not yet expired.
- Cache microapps idToken and use that idToken as long as it is not expired
=> Cache microapps idToken

web/src/components/common/Card.tsx, web/src/components/common/ListingCard.tsx, web/src/components/customer/my-commits/CommitStatusBadge.tsx, web/src/components/customer/my-commits/ListingCardWithCommitStatus.tsx, web/src/components/design-samples/index.tsx
Merge after #174 
- Added `ListingCardWithCommitStatus` which displays the customer's commit status of the listing. [(UI mock](https://www.figma.com/file/x0PWXRWxwSopiixYv41mK7/GPay-GroupBuy?node-id=1%3A40239))
- Added some samples to the design-samples page
**TODO for future PRs**
- Fix Card height to follow height of content instead of height of image (see screenshots to see what I mean)
* Not too sure when this problem happened but it happened before this PR, so I would consider it out of scope for this PR
**This is how it looks like now**
**This is how it should look like after I fix the Card height bug**
Fetch my branch and 
```
cd web
yarn
yarn start
```
And navigate to `http://localhost:3000/design-samples`.
=> Add listing card with commit status

web/src/components/common/CardImage.tsx
Merge after #176 
- Fixed card image height. Now card height follows height of content (with min height of 120px), instead of following the height of the image.
Fetch my branch and 
```
cd web
yarn
yarn start
```
And navigate to `http://localhost:3000/design-samples`.
=> Fix card img height

web/src/components/common/ListingCard.tsx, web/src/components/customer/my-commits/Commits.tsx, web/src/interfaces.ts
- Added listing cards with commit status to My Commits page
**TODO for this PR:**
=> Add listing cards to My Commits page

web/src/components/customer/listing-details/index.tsx
- Renamed `xContext` to `xProvider` in listing-details to standardise usage of contexts. (we use `xProvider` in every other file and it is also better because it is more reflective that it is a `Context.Provider`)
=> Rename xContext to xProvider to standardise

web/src/components/common/hooks/useLocalStorage.ts, web/src/components/customer/contexts/CustomerContext.tsx, web/src/components/customer/explore/index.tsx
Closes #186
**Please read #186 for background of this PR**
- Added `isExistingCustomer` flag to localstorage so that we can identity if it is an existing customer
* If existing customer, CustomerContext will log in customer when they enter the app
* else, do nothing, retain original behaviour
- Added `useLocalStorageHook` that handles setting and getting of state to persist in localstorage
- Removed "Get Identity" button on Explore page because we don't need it anymore :) 
This is how localstorage looks like after I tried logging in once (retains after page refreshes)
=> Store whether customer is existing customer in localstorage

web/src/components/customer/listing-details/ActionBar.tsx, web/src/components/customer/listing-details/index.tsx, web/src/components/customer/listing-details/interfaces.ts, web/src/components/customer/my-commits/Commits.tsx
- Directly lead customers to payment flow from My Commits "Pay" button
* Done by adding `attemptPayment` to the location state.
**Clicking on the first listing**
**Will directly lead you to:**
When user clicks on "Back" in the prompt, user will see the listing details page
Clicking on other listings in My Commits page that are not ready for payment will not trigger the prompt
=> Directly lead customers to payment flow from My Commits "Pay" button

web/src/components/common/MobilePrompt.tsx, web/src/components/customer/listing-details/CommitFeedbackPrompt.tsx, web/src/components/customer/listing-details/contexts/CommitContext.tsx, web/src/components/customer/listing-details/contexts/CommitFeedbackPromptContext.tsx
- Adding a loading prompt which opens when payment is processing
**Screenshot demo for what happens after clicking confirm**
=> Add loading prompt while processing payment

web/src/api.ts, web/src/components/common/FormRow.tsx, web/src/components/customer/listing-details/contexts/CommitContext.tsx, web/src/components/customer/listing-details/hooks/useFulfilmentDetailsForm.ts, web/src/interfaces.ts
To be merged after #195 
Part of #167 
- Added checkbox in fulfilment details form which allows customer to save their delivery details for future reference
**TODOs, not in this PR:**
- Autofill saved defaultFulfilmentDetails the next time user pays
**Datastore reflects submitted fulfilment details in `defaultFulfilmentDetails`**
=> Add set default checkbox to fulfillment details form

server/src/index.ts, server/src/middleware/error-mapper.ts, server/src/storage/datastore.ts, server/src/utils/storage-errors.ts, server/tests/integration/customers.test.ts, server/tests/integration/merchants.test.ts
Closes #210 
- Handle datastore layer errors and throw them as the appropriate `StorageError`s
- Added `error-mapper` middleware which maps each `StorageError` to a `HttpError` and throws it as the appropriate `HttpError`
- Modified tests to test for the exact status codes
=> Handle errors in datastore layer

server/src/api/commits.ts, server/src/api/customers.ts, server/src/custom-typings/express/index.d.ts, server/src/middleware/__mocks__/customer-access-control.ts, server/src/middleware/customer-access-control.ts, server/src/services/commits.ts, server/tests/integration/commits.test.ts, server/tests/integration/customers.test.ts
Closes #119
Previously, we only check for authentication of customers, and did not have access control restrictions. This means that as long as I have a valid token, I can make requests to modify another customer's commits and customer data. This is not desirable and this PR fixes this by adding a layer of access control to restricted customer endpoints. 
- Added access control middleware that checks if customer is authorized to access/modify the resource they have requested
* This middleware requires a prior middleware to add an authorized gpay id to `req.authorizedCustomerGPayId` before it can be checked in the `customerAccessControl` middleware. 
(Initially, I wanted `customerAccessControl` middleware to be a higher order function (as seen in the very first commit of this PR), but it …
=> Add customer access control middlewares

server/src/interfaces.ts, server/src/middleware/validation/phone-number.ts, server/tests/fixtures/customers.ts, server/tests/integration/customers.test.ts
To be merged after #214 
- In view of the addition of `gpayContactNumber` to `CustomerPayload` as seen in #213, this PR updates `contactNumber` format to have a space between country code and the national number, to be consistent with how gpay stores their phone numbers
=> Update contact number format

server/src/api/customers.ts, server/src/constants/default-payload.ts, server/src/interfaces.ts, server/src/middleware/validation/phone-number.ts, server/src/services/customers.ts, server/tests/fixtures/customers.ts
Part of #217
To be merged after #215 
- Added `gpayContactNumber` field to `CustomerPayload` to allow #213 as the Spot API requires the customer's contact number in gpay in order for our Spot to send messages to the customers
* We initially wanted to use a [Payment recipient](https://developers.google.com/pay/spot/eap/reference/messages-api#payment-recipient) but we are unable to call that payments API, so we settled with [Phone Number recipient](https://developers.google.com/pay/spot/eap/reference/messages-api#phone-number-recipient)
- When an existing customer signs in with a different `gpayContactNumber` from its previous value, we will update the `gpayContactNumber` of the customer to the newer one 
* This is because in GPay, customers can change their phone numbers and we will have …
=> Update gpayContactNumber upon customer login

web/.eslintrc.json, web/package.json, web/src/api.ts, web/src/components/common/FormRow.tsx, web/src/components/common/contexts/FormPropsContext.tsx, web/src/components/customer/listing-details/hooks/useFulfilmentDetailsForm.ts, web/src/microapps.ts, web/src/utils/phone-number/index.ts, web/src/utils/phone-number/phone-number.test.ts
To be merged after #218 
Closes #163, Closes #167
- Autofill fulfilment details form for customer
* If they have previously checked the `Use as default` checkbox when paying for an item, the form will now autofill with the exact same delivery details the next time the fulfilment details form pops up
* If not, the form will autofill the contact number portion with their `gpayContactNumber`
**This is how the Datastore entity for this user looks like**
**Autofill with `defaultFulfilmentDetails`**
**Autofill with `gpayContactNumber` (I removed the default details fields to test this flow)**
=> Autofill fulfilment details form

web/src/components/common/MobilePrompt.tsx, web/src/components/customer/contexts/CustomerContext.tsx, web/src/components/customer/listing-details/CommitFeedbackPrompt.tsx, web/src/microapps.ts
To be merged after #218 
- Added fallback UI for flows that require login (both identity and phone number permissions must be granted, else fallback UI will show)
=> Add phone number fallback UI for flows that require login

web/src/components/common/FormRow.tsx
- Instead of setting as children for the default value of the textarea, change to use `defaultValue` prop instead. This silenced a warning from react which indicated that we should use `defaultValue` prop instead
=> Use defaultValue prop instead of children for textarea 

web/src/components/customer/listing-details/contexts/CommitContext.tsx
- Added loading prompt for commiting and uncommitting, before the confirmation/failure prompt appears
* uncommitting does not have a confirmation prompt if successful, so we have to explicitly ask the prompt to close after a successful uncommit with `onClosePrompt()`
After clicking Commit for a listing:
=> Add loading prompt for commiting and uncommitting

web/src/components/common/MobilePrompt.tsx
- Made `text-align: center` only apply to `p` tags, so as not to affect the text alignment of other text in a prompt
Previously, the `text-align: center` in MobilePrompt was causing misaligned form labels:
This PR fixes it:
=> Fix misaligned form labels

web/src/api.ts, web/src/components/customer/listing-details/CommitFeedbackPrompt.tsx, web/src/components/customer/listing-details/contexts/CommitContext.tsx, web/src/components/customer/listing-details/contexts/CommitFeedbackPromptContext.tsx
- Show a generic commit feedback error prompt when committing, uncommitting, or paying for a commit fails
* Due to time constraint, we will use this generic error prompt. If time permits, we can set up more specific error prompts.
This is how it looks like:
=> Add generic commit feedback error prompt

web/src/index.css
- Set muicss primary color to green and disabled color to gray to match our UI Mock 
**Green primary buttons**
**Gray disabled button**
=> Customise primary and disabled muicss button colors

web/src/components/common/ListingCard.tsx, web/src/components/customer/my-commits/CommitStatusBadge.tsx, web/src/components/customer/my-commits/ListingCardWithCommitStatus.tsx
- Fixed bug in My Commits page listing commit status badge, where the text in the badge tend to wrap in weird manners
Before:
After:
=> Fix word wrap bug in commit status badge

web/src/components/common/MobilePrompt.tsx, web/src/index.css
- I realised that the primary color is switching back to blue occasionally, and dug deeper to find out that there were psuedo classes that I was missing out, so this PR adds that in
- Set background of button in mobile prompt to none so that disabled buttons don't have a gray background
=> Fix muicss primary and disabled color
